steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/daily-halacha-translate', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/daily-halacha-translate']
  
  # Deploy container image to Cloud Run (Free Tier Optimized)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'daily-halacha-translate'
      - '--image'
      - 'gcr.io/$PROJECT_ID/daily-halacha-translate'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '0.5'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '2'
      - '--timeout'
      - '60s'
      - '--concurrency'
      - '80'

images:
  - 'gcr.io/$PROJECT_ID/daily-halacha-translate' 