#!/bin/bash

echo "🔍 Render.com to Google Cloud Run Migration Helper"
echo "=================================================="
echo ""

echo "📋 Please provide the following information from your Render.com dashboard:"
echo ""

echo "1. Go to your Render.com dashboard"
echo "2. Navigate to your service"
echo "3. Go to 'Environment' tab"
echo "4. Copy the following environment variables:"
echo ""

echo "Required Environment Variables:"
echo "-----------------------------"
echo "VERIFY_TOKEN=your_verify_token"
echo "WHATSAPP_TOKEN=your_whatsapp_token"
echo "WHATSAPP_PHONE_NUMBER_ID=your_phone_number_id"
echo "GEMINI_API_KEY=your_gemini_api_key"
echo ""

echo "Optional Environment Variables:"
echo "-----------------------------"
echo "PORT=8080 (will be set automatically)"
echo ""

echo "📝 After you have these values, you can set them in Google Cloud Run using:"
echo ""
echo "gcloud run services update daily-halacha-translate \\"
echo "  --set-env-vars VERIFY_TOKEN=your_verify_token \\"
echo "  --set-env-vars WHATSAPP_TOKEN=your_whatsapp_token \\"
echo "  --set-env-vars WHATSAPP_PHONE_NUMBER_ID=your_phone_number_id \\"
echo "  --set-env-vars GEMINI_API_KEY=your_gemini_api_key"
echo ""

echo "🔗 Your current Render.com webhook URL:"
echo "Check your Render.com service URL and note it for updating WhatsApp webhook later"
echo ""

echo "📊 Migration Checklist:"
echo "☐ Install Google Cloud CLI"
echo "☐ Create Google Cloud Project"
echo "☐ Enable required APIs"
echo "☐ Authenticate with gcloud"
echo "☐ Deploy to Cloud Run"
echo "☐ Set environment variables"
echo "☐ Update WhatsApp webhook URL"
echo "☐ Test the service"
echo "☐ Stop Render.com service"
echo "" 